language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

env: 
  global:
    - MEMCACHE_HOST=localhost

services:
  - memcached

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

install:
  - composer require squizlabs/php_codesniffer
  - composer require phpmd/phpmd

before_script:
  - phpenv config-add tests/php-travis.ini

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode

