language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.0
  - 5.6
  - 5.5
  - hhvm

env: 
  global:
    - MEMCACHE_HOST=localhost
    - REDIS_URI=redis://localhost

services:
  - memcached
  - redis-server

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
    - php: 7.0

before_install:
  - phpenv config-add tests/php-travis.ini

install:
  - composer require squizlabs/php_codesniffer
  - composer require phpmd/phpmd

script:
  - vendor/bin/phpunit
  - vendor/bin/phpcs --standard=PSR2 classes/ tests/
  - vendor/bin/phpmd classes/ text cleancode,codesize,controversial,design,naming,unusedcode

